apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx-git
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/kubeplusplus/gitops # make sure you change this url to your repository
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
