apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-helm-release
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-helm
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      hosts:
        - host: nginx-helm-release.local
          paths:
            - /
