apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: files
  namespace: anonymous-sharing
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "8.7.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
    ingress:
      enabled: true
      hostname: anonymous-sharing-files.kubeplusplus.com
      extraVolumes:
        - name: files-storage
          persistentVolumeClaim:
            claimName: anonymous-sharing-files-volume-claim
      extraVolumeMounts:
        - name: files-storage
          mountPath: /app