apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anonymous-sharing-files-volume-claim
  namespace: anonymous-sharing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi