apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgBycD/pCkqKVBjaKeh/93CANE+kLF6ESrAMFNFu8Bn6KHipdzndpogv8FIqsVlIrJrg4qIKey/GP9n3pLkkKQZyppZrAKZzpSX+5qiddbSsZPTl270dlkXGMlsnDm6I/y7sHWxBBFOQls53o3kKoXiQ1B70QKSs4VZCTI8974ZtQs3YMdJZI9JHhRHvrWaLHf41z6N1AZXeyQHiuHMiZlFveOG788U7l1hAka8kwL3x+QaKaAlh4G2EUgc+Z1JwMiL9AqgPyTesNfiZjJpPC1sBqSNM7AU30Se2siodwe7AbvIUm0yFZe5Ferx1a/9dxjp7LdyXw2gOFVL0gHvjgI/fMrsFaVJ9m9mLOPVaYvMjfJx5G9f43l5cwykFSXQPzyZSyZmwp0d6Bkoq4QAygokFUFVmWGD1kE17rNrpWPGKKyBfl4+4eluV9Xv2AK0P1GHIqe6BZ5RJi97krZ3FvE+gXFfXw46JdZ+cyk08bwZU0SLosQCtShcGdfc19tfJ34nEVSsFnEYIfY0iGecRubl1llmA19OzmPDcx66dZ5c5wVwbP03YZhMhMMkION32aQb/Z7B4X/im4UP8O/QaUJHQa+nDYJ95dyrdE2S0ZCDGyRERQMEFNFyUMGM/q+Q6X+txyRAC+tv3676iFgcSvCuhbN+TvumdZEzpHl7kNXAq22yRfI1q3B22BqkPoiVsok/87XlspBp4M6g=
    user: AgAfaMwD+dBRr9XcucjqK7rp17qSIt0w9S3cKrDpZT1dLUYU+iApLVotGLBmoMVh5VQJnQKgfNLdyjKef5v5MZbzndnkXysIIXCHJQjsJNl/zOk97oZpQ6O4ycgDqj1Bi2rTTUawofnNXOUVSbXa4goLTBO/941dBaqjib9mcFFzq+kMv37HSELKsW8vqzZGL5B6ycfqM1QL0dQ+Z8BszamFt+i5tBTv1OfUDPvJZVxSfBErokEf6WB/X7t4u15DGsZ3FD8RwKededdmzlKvGCU2A2fMpUUMH5DSaHPx5s7/CV7EgAlSINN+6ah8EN9aaqxyzz8kwBBrmqx9BBcGmj7zgWbMQOLed0FLKu/Dj78hX4M6TQzDanvILZAZQwsJ5r0HIndlq038FSUkvCrHxVBw7Ov1nfCzRTHlIqjCm6n6NfGAcfbV3WvbyDdidIl+K2SYEzCzD8WrSsCOez6TJyrF0Pb8ULXGBRonZKs8clRPotd7AuN/Pmw6D4n6ZyiCCJzoAAMhN3uXnqeSt6oIAG1UdmXwitdSXbyW3vgqe36v/fGfkJiWfOpPB0eEFqfmPIV5+4QqpL5W27SS3n1W0hNs+u3ccyiiyNQf45d+LnW/ZeJyzPcNEIG2PUTwIvOB7sO5txFIGqckdBsUlPoLEnnzh7IQC8IQAT3+jeHDW2g2t8iDArrLbBMnum8YmBDNu4Thly+lFQ==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default

